include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Mets ici les règles que tu veux SILENCER globalement
    unused_import: ignore
    unused_local_variable: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    avoid_print: ignore

linter:
  rules:
    # Tu peux aussi laisser vide:
    # (aucune règle supplémentaire activée)
