name: flutter_ecommerce_app_v2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.2+1

environment:
  sdk: ^3.8.1
#--------------- PACKAGES --------------#
dependencies:
  flutter:
    sdk: flutter
  # Utility Packages
  http: ^1.5.0
  intl: ^0.20.2
  logger: ^2.6.1
  url_launcher: ^6.3.2
  smooth_page_indicator: ^1.2.1
  connectivity_plus: ^6.1.5
  flutter_native_splash: ^2.4.6
  lottie: ^3.3.1
  shimmer: ^3.0.0
  image_picker: ^1.2.0
  #seprator
  dotted_line: ^3.2.2
  # Google Map
  flutter_polyline_points: ^2.1.0
  google_maps_flutter: ^2.12.1
  geolocator: ^13.0.4
  geocoding: ^3.0.0

  #Firebase Packages 
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  firebase_storage: ^13.0.0
  cloud_firestore: ^6.0.0
  google_sign_in: ^7.1.1
  #timeline
  timelines_plus: 

  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  #State management
  get:
  get_storage:
  hive: ^2.2.3
  hive_flutter: ^1.1.0


  #Product Specific
  carousel_slider:
  readmore:
  flutter_rating_bar:
  cached_network_image:
  #--------------- PACKAGES END --------------#
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/
    - assets/animations/
    - assets/banners/
    - assets/icons/categories/
    - assets/icons/payment_methods/
    - assets/products/
    - assets/brands/
    - assets/seed/plan.json
  fonts:
    - family: 'Nunito'
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 800
